import 'package:flutter/material.dart';

/// App Translations - Contains all translatable strings
class AppStrings {
  static Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Common
      'app_name': 'Queez',
      'cancel': 'Cancel',
      'save': 'Save',
      'done': 'Done',
      'delete': 'Delete',
      'edit': 'Edit',
      'ok': 'OK',
      'yes': 'Yes',
      'no': 'No',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'search': 'Search',
      'back': 'Back',
      'next': 'Next',
      'continue_text': 'Continue',
      'skip': 'Skip',

      // Settings
      'settings': 'Settings',
      'account': 'Account',
      'edit_profile': 'Edit Profile',
      'update_profile_info': 'Update your profile information',
      'change_password': 'Change Password',
      'update_password': 'Update your password',
      'preferences': 'Preferences',
      'language': 'Language',
      'theme': 'Theme',
      'light_mode': 'Light mode',
      'dark_mode': 'Dark mode',
      'about': 'About',
      'about_app': 'About Queez',
      'version': 'Version',
      'privacy_policy': 'Privacy Policy',
      'read_privacy_policy': 'Read our privacy policy',
      'terms_of_service': 'Terms of Service',
      'sign_out': 'Sign Out',
      'sign_out_confirm': 'Are you sure you want to sign out?',
      'delete_account': 'Delete Account',
      'delete_account_warning': 'This will permanently delete your account and all associated data. This action cannot be undone.',
      'danger_zone': 'Danger Zone',
      'select_language': 'Select Language',

      // Profile
      'profile': 'Profile',
      'name': 'Name',
      'username': 'Username',
      'email': 'Email',
      'age': 'Age',
      'role': 'Role',
      'subject_area': 'Subject Area',
      'experience_level': 'Experience Level',
      'interests': 'Interests',

      // Library
      'library': 'Library',
      'my_content': 'My Content',
      'quizzes': 'Quizzes',
      'flashcards': 'Flashcards',
      'notes': 'Notes',
      'study_sets': 'Study Sets',
      'create': 'Create',
      'explore': 'Explore',

      // Quiz
      'quiz': 'Quiz',
      'start_quiz': 'Start Quiz',
      'question': 'Question',
      'correct': 'Correct',
      'incorrect': 'Incorrect',
      'score': 'Score',
      'time_remaining': 'Time Remaining',
      'submit': 'Submit',
      'finish': 'Finish',

      // Auth
      'login': 'Login',
      'sign_up': 'Sign Up',
      'email_address': 'Email Address',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': "Don't have an account?",
      'already_have_account': 'Already have an account?',

      // Navigation
      'home': 'Home',
      'dashboard': 'Dashboard',

      // Greetings
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',

      // Messages
      'profile_updated': 'Profile updated successfully!',
      'password_reset_sent': 'Password reset link sent to your email',
      'language_changed': 'Language changed successfully',
    },
    'es': {
      // Common
      'app_name': 'Queez',
      'cancel': 'Cancelar',
      'save': 'Guardar',
      'done': 'Hecho',
      'delete': 'Eliminar',
      'edit': 'Editar',
      'ok': 'OK',
      'yes': 'Sí',
      'no': 'No',
      'loading': 'Cargando...',
      'error': 'Error',
      'success': 'Éxito',
      'search': 'Buscar',
      'back': 'Atrás',
      'next': 'Siguiente',
      'continue_text': 'Continuar',
      'skip': 'Omitir',

      // Settings
      'settings': 'Configuración',
      'account': 'Cuenta',
      'edit_profile': 'Editar Perfil',
      'update_profile_info': 'Actualiza tu información de perfil',
      'change_password': 'Cambiar Contraseña',
      'update_password': 'Actualiza tu contraseña',
      'preferences': 'Preferencias',
      'language': 'Idioma',
      'theme': 'Tema',
      'light_mode': 'Modo claro',
      'dark_mode': 'Modo oscuro',
      'about': 'Acerca de',
      'about_app': 'Acerca de Queez',
      'version': 'Versión',
      'privacy_policy': 'Política de Privacidad',
      'read_privacy_policy': 'Lee nuestra política de privacidad',
      'terms_of_service': 'Términos de Servicio',
      'sign_out': 'Cerrar Sesión',
      'sign_out_confirm': '¿Estás seguro de que quieres cerrar sesión?',
      'delete_account': 'Eliminar Cuenta',
      'delete_account_warning': 'Esto eliminará permanentemente tu cuenta y todos los datos asociados. Esta acción no se puede deshacer.',
      'danger_zone': 'Zona de Peligro',
      'select_language': 'Seleccionar Idioma',

      // Profile
      'profile': 'Perfil',
      'name': 'Nombre',
      'username': 'Usuario',
      'email': 'Correo',
      'age': 'Edad',
      'role': 'Rol',
      'subject_area': 'Área de Estudio',
      'experience_level': 'Nivel de Experiencia',
      'interests': 'Intereses',

      // Library
      'library': 'Biblioteca',
      'my_content': 'Mi Contenido',
      'quizzes': 'Cuestionarios',
      'flashcards': 'Tarjetas',
      'notes': 'Notas',
      'study_sets': 'Conjuntos de Estudio',
      'create': 'Crear',
      'explore': 'Explorar',

      // Quiz
      'quiz': 'Cuestionario',
      'start_quiz': 'Iniciar Cuestionario',
      'question': 'Pregunta',
      'correct': 'Correcto',
      'incorrect': 'Incorrecto',
      'score': 'Puntuación',
      'time_remaining': 'Tiempo Restante',
      'submit': 'Enviar',
      'finish': 'Terminar',

      // Auth
      'login': 'Iniciar Sesión',
      'sign_up': 'Registrarse',
      'email_address': 'Correo Electrónico',
      'password': 'Contraseña',
      'confirm_password': 'Confirmar Contraseña',
      'forgot_password': '¿Olvidaste tu contraseña?',
      'dont_have_account': '¿No tienes cuenta?',
      'already_have_account': '¿Ya tienes cuenta?',

      // Navigation
      'home': 'Inicio',
      'dashboard': 'Panel',

      // Greetings
      'good_morning': 'Buenos Días',
      'good_afternoon': 'Buenas Tardes',
      'good_evening': 'Buenas Noches',

      // Messages
      'profile_updated': '¡Perfil actualizado correctamente!',
      'password_reset_sent': 'Enlace de restablecimiento enviado a tu correo',
      'language_changed': 'Idioma cambiado correctamente',
    },
    'fr': {
      'app_name': 'Queez',
      'cancel': 'Annuler',
      'save': 'Enregistrer',
      'done': 'Terminé',
      'delete': 'Supprimer',
      'edit': 'Modifier',
      'ok': 'OK',
      'yes': 'Oui',
      'no': 'Non',
      'loading': 'Chargement...',
      'error': 'Erreur',
      'success': 'Succès',
      'search': 'Rechercher',
      'back': 'Retour',
      'next': 'Suivant',
      'continue_text': 'Continuer',
      'skip': 'Passer',
      'settings': 'Paramètres',
      'account': 'Compte',
      'edit_profile': 'Modifier le Profil',
      'update_profile_info': 'Mettre à jour vos informations',
      'change_password': 'Changer le Mot de Passe',
      'update_password': 'Mettre à jour votre mot de passe',
      'preferences': 'Préférences',
      'language': 'Langue',
      'theme': 'Thème',
      'light_mode': 'Mode clair',
      'dark_mode': 'Mode sombre',
      'about': 'À propos',
      'about_app': 'À propos de Queez',
      'version': 'Version',
      'privacy_policy': 'Politique de Confidentialité',
      'read_privacy_policy': 'Lire notre politique de confidentialité',
      'sign_out': 'Déconnexion',
      'sign_out_confirm': 'Êtes-vous sûr de vouloir vous déconnecter?',
      'delete_account': 'Supprimer le Compte',
      'danger_zone': 'Zone Dangereuse',
      'select_language': 'Sélectionner la Langue',
      'profile': 'Profil',
      'library': 'Bibliothèque',
      'my_content': 'Mon Contenu',
      'quizzes': 'Quiz',
      'flashcards': 'Cartes Mémoire',
      'notes': 'Notes',
      'study_sets': 'Ensembles d\'Étude',
      'interests': 'Intérêts',
      'home': 'Accueil',
      'dashboard': 'Tableau de Bord',
      'good_morning': 'Bonjour',
      'good_afternoon': 'Bon Après-midi',
      'good_evening': 'Bonsoir',
      'language_changed': 'Langue changée avec succès',
    },
    'de': {
      // Common
      'app_name': 'Queez',
      'cancel': 'Abbrechen',
      'save': 'Speichern',
      'done': 'Fertig',
      'delete': 'Löschen',
      'edit': 'Bearbeiten',
      'ok': 'OK',
      'yes': 'Ja',
      'no': 'Nein',
      'loading': 'Laden...',
      'error': 'Fehler',
      'success': 'Erfolg',
      'search': 'Suchen',
      'back': 'Zurück',
      'next': 'Weiter',
      'continue_text': 'Fortfahren',
      'skip': 'Überspringen',

      // Settings
      'settings': 'Einstellungen',
      'account': 'Konto',
      'edit_profile': 'Profil Bearbeiten',
      'update_profile_info': 'Aktualisieren Sie Ihre Profilinformationen',
      'change_password': 'Passwort Ändern',
      'update_password': 'Aktualisieren Sie Ihr Passwort',
      'preferences': 'Präferenzen',
      'language': 'Sprache',
      'theme': 'Thema',
      'light_mode': 'Heller Modus',
      'dark_mode': 'Dunkler Modus',
      'about': 'Über',
      'about_app': 'Über Queez',
      'version': 'Version',
      'privacy_policy': 'Datenschutzrichtlinie',
      'read_privacy_policy': 'Lesen Sie unsere Datenschutzrichtlinie',
      'terms_of_service': 'Nutzungsbedingungen',
      'sign_out': 'Abmelden',
      'sign_out_confirm': 'Möchten Sie sich wirklich abmelden?',
      'delete_account': 'Konto Löschen',
      'delete_account_warning': 'Dadurch werden Ihr Konto und alle zugehörigen Daten dauerhaft gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.',
      'danger_zone': 'Gefahrenzone',
      'select_language': 'Sprache Auswählen',

      // Profile
      'profile': 'Profil',
      'name': 'Name',
      'username': 'Benutzername',
      'email': 'E-Mail',
      'age': 'Alter',
      'role': 'Rolle',
      'subject_area': 'Fachbereich',
      'experience_level': 'Erfahrungsstufe',
      'interests': 'Interessen',

      // Library
      'library': 'Bibliothek',
      'my_content': 'Meine Inhalte',
      'quizzes': 'Quiz',
      'flashcards': 'Karteikarten',
      'notes': 'Notizen',
      'study_sets': 'Lernsets',
      'create': 'Erstellen',
      'explore': 'Entdecken',

      // Quiz
      'quiz': 'Quiz',
      'start_quiz': 'Quiz Starten',
      'question': 'Frage',
      'correct': 'Richtig',
      'incorrect': 'Falsch',
      'score': 'Punktzahl',
      'time_remaining': 'Verbleibende Zeit',
      'submit': 'Absenden',
      'finish': 'Beenden',

      // Auth
      'login': 'Anmelden',
      'sign_up': 'Registrieren',
      'email_address': 'E-Mail-Adresse',
      'password': 'Passwort',
      'confirm_password': 'Passwort Bestätigen',
      'forgot_password': 'Passwort Vergessen?',
      'dont_have_account': 'Noch kein Konto?',
      'already_have_account': 'Bereits ein Konto?',

      // Navigation
      'home': 'Startseite',
      'dashboard': 'Dashboard',

      // Greetings
      'good_morning': 'Guten Morgen',
      'good_afternoon': 'Guten Tag',
      'good_evening': 'Guten Abend',

      // Messages
      'profile_updated': 'Profil erfolgreich aktualisiert!',
      'password_reset_sent': 'Link zum Zurücksetzen des Passworts wurde gesendet',
      'language_changed': 'Sprache erfolgreich geändert',
    },
    'hi': {
      // Common
      'app_name': 'Queez',
      'cancel': 'रद्द करें',
      'save': 'सहेजें',
      'done': 'हो गया',
      'delete': 'हटाएं',
      'edit': 'संपादित करें',
      'ok': 'ठीक है',
      'yes': 'हां',
      'no': 'नहीं',
      'loading': 'लोड हो रहा है...',
      'error': 'त्रुटि',
      'success': 'सफलता',
      'search': 'खोजें',
      'back': 'वापस',
      'next': 'अगला',
      'continue_text': 'जारी रखें',
      'skip': 'छोड़ें',

      // Settings
      'settings': 'सेटिंग्स',
      'account': 'खाता',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'update_profile_info': 'अपनी प्रोफ़ाइल जानकारी अपडेट करें',
      'change_password': 'पासवर्ड बदलें',
      'update_password': 'अपना पासवर्ड अपडेट करें',
      'preferences': 'प्राथमिकताएं',
      'language': 'भाषा',
      'theme': 'थीम',
      'light_mode': 'लाइट मोड',
      'dark_mode': 'डार्क मोड',
      'about': 'के बारे में',
      'about_app': 'Queez के बारे में',
      'version': 'संस्करण',
      'privacy_policy': 'गोपनीयता नीति',
      'read_privacy_policy': 'हमारी गोपनीयता नीति पढ़ें',
      'terms_of_service': 'सेवा की शर्तें',
      'sign_out': 'साइन आउट',
      'sign_out_confirm': 'क्या आप वाकई साइन आउट करना चाहते हैं?',
      'delete_account': 'खाता हटाएं',
      'delete_account_warning': 'यह आपके खाते और सभी संबंधित डेटा को स्थायी रूप से हटा देगा। यह क्रिया पूर्ववत नहीं की जा सकती।',
      'danger_zone': 'खतरनाक क्षेत्र',
      'select_language': 'भाषा चुनें',

      // Profile
      'profile': 'प्रोफ़ाइल',
      'name': 'नाम',
      'username': 'उपयोगकर्ता नाम',
      'email': 'ईमेल',
      'age': 'उम्र',
      'role': 'भूमिका',
      'subject_area': 'विषय क्षेत्र',
      'experience_level': 'अनुभव स्तर',
      'interests': 'रुचियां',

      // Library
      'library': 'लाइब्रेरी',
      'my_content': 'मेरी सामग्री',
      'quizzes': 'क्विज़',
      'flashcards': 'फ्लैशकार्ड',
      'notes': 'नोट्स',
      'study_sets': 'अध्ययन सेट',
      'create': 'बनाएं',
      'explore': 'खोजें',

      // Quiz
      'quiz': 'क्विज़',
      'start_quiz': 'क्विज़ शुरू करें',
      'question': 'प्रश्न',
      'correct': 'सही',
      'incorrect': 'गलत',
      'score': 'स्कोर',
      'time_remaining': 'शेष समय',
      'submit': 'जमा करें',
      'finish': 'समाप्त',

      // Auth
      'login': 'लॉगिन',
      'sign_up': 'साइन अप',
      'email_address': 'ईमेल पता',
      'password': 'पासवर्ड',
      'confirm_password': 'पासवर्ड की पुष्टि करें',
      'forgot_password': 'पासवर्ड भूल गए?',
      'dont_have_account': 'खाता नहीं है?',
      'already_have_account': 'पहले से खाता है?',

      // Navigation
      'home': 'होम',
      'dashboard': 'डैशबोर्ड',

      // Greetings
      'good_morning': 'सुप्रभात',
      'good_afternoon': 'नमस्कार',
      'good_evening': 'शुभ संध्या',

      // Messages
      'profile_updated': 'प्रोफ़ाइल सफलतापूर्वक अपडेट हुई!',
      'password_reset_sent': 'पासवर्ड रीसेट लिंक आपके ईमेल पर भेजा गया',
      'language_changed': 'भाषा सफलतापूर्वक बदल गई',
    },
    'ar': {
      // Common
      'app_name': 'Queez',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'done': 'تم',
      'delete': 'حذف',
      'edit': 'تعديل',
      'ok': 'موافق',
      'yes': 'نعم',
      'no': 'لا',
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'success': 'نجاح',
      'search': 'بحث',
      'back': 'رجوع',
      'next': 'التالي',
      'continue_text': 'متابعة',
      'skip': 'تخطي',

      // Settings
      'settings': 'الإعدادات',
      'account': 'الحساب',
      'edit_profile': 'تعديل الملف الشخصي',
      'update_profile_info': 'تحديث معلومات ملفك الشخصي',
      'change_password': 'تغيير كلمة المرور',
      'update_password': 'تحديث كلمة المرور',
      'preferences': 'التفضيلات',
      'language': 'اللغة',
      'theme': 'المظهر',
      'light_mode': 'الوضع الفاتح',
      'dark_mode': 'الوضع الداكن',
      'about': 'حول',
      'about_app': 'حول Queez',
      'version': 'الإصدار',
      'privacy_policy': 'سياسة الخصوصية',
      'read_privacy_policy': 'اقرأ سياسة الخصوصية',
      'terms_of_service': 'شروط الخدمة',
      'sign_out': 'تسجيل الخروج',
      'sign_out_confirm': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'delete_account': 'حذف الحساب',
      'delete_account_warning': 'سيؤدي هذا إلى حذف حسابك وجميع البيانات المرتبطة به بشكل دائم. لا يمكن التراجع عن هذا الإجراء.',
      'danger_zone': 'منطقة الخطر',
      'select_language': 'اختر اللغة',

      // Profile
      'profile': 'الملف الشخصي',
      'name': 'الاسم',
      'username': 'اسم المستخدم',
      'email': 'البريد الإلكتروني',
      'age': 'العمر',
      'role': 'الدور',
      'subject_area': 'مجال الدراسة',
      'experience_level': 'مستوى الخبرة',
      'interests': 'الاهتمامات',

      // Library
      'library': 'المكتبة',
      'my_content': 'محتواي',
      'quizzes': 'الاختبارات',
      'flashcards': 'البطاقات التعليمية',
      'notes': 'الملاحظات',
      'study_sets': 'مجموعات الدراسة',
      'create': 'إنشاء',
      'explore': 'استكشاف',

      // Quiz
      'quiz': 'اختبار',
      'start_quiz': 'بدء الاختبار',
      'question': 'سؤال',
      'correct': 'صحيح',
      'incorrect': 'خطأ',
      'score': 'النتيجة',
      'time_remaining': 'الوقت المتبقي',
      'submit': 'إرسال',
      'finish': 'إنهاء',

      // Auth
      'login': 'تسجيل الدخول',
      'sign_up': 'إنشاء حساب',
      'email_address': 'عنوان البريد الإلكتروني',
      'password': 'كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'forgot_password': 'نسيت كلمة المرور؟',
      'dont_have_account': 'ليس لديك حساب؟',
      'already_have_account': 'لديك حساب بالفعل؟',

      // Navigation
      'home': 'الرئيسية',
      'dashboard': 'لوحة التحكم',

      // Greetings
      'good_morning': 'صباح الخير',
      'good_afternoon': 'مساء الخير',
      'good_evening': 'مساء الخير',

      // Messages
      'profile_updated': 'تم تحديث الملف الشخصي بنجاح!',
      'password_reset_sent': 'تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني',
      'language_changed': 'تم تغيير اللغة بنجاح',
    },
    'zh': {
      // Common
      'app_name': 'Queez',
      'cancel': '取消',
      'save': '保存',
      'done': '完成',
      'delete': '删除',
      'edit': '编辑',
      'ok': '确定',
      'yes': '是',
      'no': '否',
      'loading': '加载中...',
      'error': '错误',
      'success': '成功',
      'search': '搜索',
      'back': '返回',
      'next': '下一步',
      'continue_text': '继续',
      'skip': '跳过',

      // Settings
      'settings': '设置',
      'account': '账户',
      'edit_profile': '编辑资料',
      'update_profile_info': '更新您的个人信息',
      'change_password': '修改密码',
      'update_password': '更新您的密码',
      'preferences': '偏好设置',
      'language': '语言',
      'theme': '主题',
      'light_mode': '浅色模式',
      'dark_mode': '深色模式',
      'about': '关于',
      'about_app': '关于 Queez',
      'version': '版本',
      'privacy_policy': '隐私政策',
      'read_privacy_policy': '阅读我们的隐私政策',
      'terms_of_service': '服务条款',
      'sign_out': '退出登录',
      'sign_out_confirm': '确定要退出登录吗？',
      'delete_account': '删除账户',
      'delete_account_warning': '这将永久删除您的账户和所有相关数据。此操作无法撤销。',
      'danger_zone': '危险区域',
      'select_language': '选择语言',

      // Profile
      'profile': '个人资料',
      'name': '姓名',
      'username': '用户名',
      'email': '邮箱',
      'age': '年龄',
      'role': '角色',
      'subject_area': '学科领域',
      'experience_level': '经验水平',
      'interests': '兴趣爱好',

      // Library
      'library': '资料库',
      'my_content': '我的内容',
      'quizzes': '测验',
      'flashcards': '单词卡',
      'notes': '笔记',
      'study_sets': '学习集',
      'create': '创建',
      'explore': '探索',

      // Quiz
      'quiz': '测验',
      'start_quiz': '开始测验',
      'question': '问题',
      'correct': '正确',
      'incorrect': '错误',
      'score': '分数',
      'time_remaining': '剩余时间',
      'submit': '提交',
      'finish': '完成',

      // Auth
      'login': '登录',
      'sign_up': '注册',
      'email_address': '邮箱地址',
      'password': '密码',
      'confirm_password': '确认密码',
      'forgot_password': '忘记密码？',
      'dont_have_account': '没有账户？',
      'already_have_account': '已有账户？',

      // Navigation
      'home': '首页',
      'dashboard': '仪表板',

      // Greetings
      'good_morning': '早上好',
      'good_afternoon': '下午好',
      'good_evening': '晚上好',

      // Messages
      'profile_updated': '个人资料更新成功！',
      'password_reset_sent': '密码重置链接已发送到您的邮箱',
      'language_changed': '语言更改成功',
    },
    'ja': {
      'app_name': 'Queez',
      'cancel': 'キャンセル',
      'save': '保存',
      'done': '完了',
      'delete': '削除',
      'edit': '編集',
      'ok': 'OK',
      'yes': 'はい',
      'no': 'いいえ',
      'loading': '読み込み中...',
      'error': 'エラー',
      'success': '成功',
      'search': '検索',
      'settings': '設定',
      'account': 'アカウント',
      'edit_profile': 'プロフィール編集',
      'change_password': 'パスワード変更',
      'preferences': '環境設定',
      'language': '言語',
      'theme': 'テーマ',
      'sign_out': 'ログアウト',
      'delete_account': 'アカウント削除',
      'select_language': '言語を選択',
      'profile': 'プロフィール',
      'library': 'ライブラリ',
      'home': 'ホーム',
      'language_changed': '言語が正常に変更されました',
    },
    'pt': {
      'app_name': 'Queez',
      'cancel': 'Cancelar',
      'save': 'Salvar',
      'done': 'Concluído',
      'delete': 'Excluir',
      'edit': 'Editar',
      'ok': 'OK',
      'yes': 'Sim',
      'no': 'Não',
      'loading': 'Carregando...',
      'error': 'Erro',
      'success': 'Sucesso',
      'search': 'Pesquisar',
      'settings': 'Configurações',
      'account': 'Conta',
      'edit_profile': 'Editar Perfil',
      'change_password': 'Alterar Senha',
      'preferences': 'Preferências',
      'language': 'Idioma',
      'theme': 'Tema',
      'sign_out': 'Sair',
      'delete_account': 'Excluir Conta',
      'select_language': 'Selecionar Idioma',
      'profile': 'Perfil',
      'library': 'Biblioteca',
      'home': 'Início',
      'language_changed': 'Idioma alterado com sucesso',
    },
    'ru': {
      'app_name': 'Queez',
      'cancel': 'Отмена',
      'save': 'Сохранить',
      'done': 'Готово',
      'delete': 'Удалить',
      'edit': 'Редактировать',
      'ok': 'ОК',
      'yes': 'Да',
      'no': 'Нет',
      'loading': 'Загрузка...',
      'error': 'Ошибка',
      'success': 'Успех',
      'search': 'Поиск',
      'settings': 'Настройки',
      'account': 'Аккаунт',
      'edit_profile': 'Редактировать Профиль',
      'change_password': 'Изменить Пароль',
      'preferences': 'Предпочтения',
      'language': 'Язык',
      'theme': 'Тема',
      'sign_out': 'Выйти',
      'delete_account': 'Удалить Аккаунт',
      'select_language': 'Выберите Язык',
      'profile': 'Профиль',
      'library': 'Библиотека',
      'home': 'Главная',
      'language_changed': 'Язык успешно изменен',
    },
  };

  static String get(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

/// Extension for easy translation access
extension StringTranslation on String {
  String tr(BuildContext context) {
    final locale = Localizations.localeOf(context);
    return AppStrings.get(this, locale.languageCode);
  }
}
